[build]
publish = "public"
command = "hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[redirects]]
from = "https://wrongwang.netlify.com/*"
to = "https://wrong.wang/:splat"
status = 301
force = true

[[redirects]]
  from = "http://wrongwang.netlify.com/*"
  to = "http://wrong.wang/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://wrong.wang/*"
  to = "https://wrong.wang/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://wrong.wang/x/*"
  to = "https://budui.github.io/:splat"
  status = 200
  force = true
